# Generated by Django 5.0.3 on 2024-03-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_task_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images"),
        ),
    ]
